
-- --------------------------------------------------------

USE cs411baseball_db;

--
-- Table structure for table `teams`
--

DROP TABLE IF EXISTS `teams`;
CREATE TABLE IF NOT EXISTS `teams` (
  `teamid` varchar(10) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `park` varchar(100) DEFAULT NULL,
  `leagueid` varchar(5) DEFAULT NULL,
  `franchiseid` varchar(5) DEFAULT NULL,
  `divisionid` varchar(3) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `teams`
--

INSERT INTO `teams` (`teamid`, `name`, `park`, `leagueid`, `franchiseid`, `divisionid`) VALUES
('BS1', 'Boston Red Stockings', 'South End Grounds I', 'NA', 'BNA', ''),
('CH1', 'Chicago White Stockings', 'Union Base-Ball Grounds', 'NA', 'CNA', ''),
('CL1', 'Cleveland Forest Citys', 'National Association Grounds', 'NA', 'CFC', ''),
('FW1', 'Fort Wayne Kekiongas', 'Hamilton Field', 'NA', 'KEK', ''),
('NY2', 'New York Mutuals', 'Union Grounds (Brooklyn)', 'NA', 'NNA', ''),
('PH1', 'Philadelphia Athletics', 'Jefferson Street Grounds', 'NA', 'PNA', ''),
('RC1', 'Rockford Forest Citys', 'Agricultural Society Fair Grounds', 'NA', 'ROK', ''),
('TRO', 'Troy Haymakers', 'Haymakers\' Grounds', 'NA', 'TRO', ''),
('WS3', 'Washington Olympics', 'Olympics Grounds', 'NA', 'OLY', ''),
('BL1', 'Baltimore Canaries', 'Newington Park', 'NA', 'BLC', ''),
('BR1', 'Brooklyn Eckfords', 'Union Grounds', 'NA', 'ECK', ''),
('BR2', 'Brooklyn Atlantics', 'Capitoline Grounds', 'NA', 'BRA', ''),
('MID', 'Middletown Mansfields', 'Mansfield Club Grounds', 'NA', 'MAN', ''),
('WS4', 'Washington Nationals', 'Nationals Grounds', 'NA', 'NAT', ''),
('BL4', 'Baltimore Marylands', 'Newington Park', 'NA', 'MAR', ''),
('BR2', 'Brooklyn Atlantics', 'Union Grounds', 'NA', 'BRA', ''),
('ELI', 'Elizabeth Resolutes', 'Waverly Fairgrounds', 'NA', 'RES', ''),
('PH2', 'Philadelphia Whites', 'Jefferson Street Grounds', 'NA', 'PWS', ''),
('WS5', 'Washington Blue Legs', 'Olympics Grounds', 'NA', 'WBL', ''),
('CH2', 'Chicago White Stockings', '23rd Street Grounds', 'NA', 'CNA', ''),
('HR1', 'Hartford Dark Blues', 'Hartford Ball Club Grounds', 'NA', 'HNA', ''),
('KEO', 'Keokuk Westerns', 'Perry Park', 'NA', 'WES', ''),
('NH1', 'New Haven Elm Citys', 'Hamilton Park', 'NA', 'NHV', ''),
('PH3', 'Philadelphia Centennials', 'Centennial Grounds', 'NA', 'CEN', ''),
('SL1', 'St. Louis Red Stockings', 'Red Stocking Baseball Park', 'NA', 'SLR', ''),
('SL2', 'St. Louis Brown Stockings', 'Grand Avenue Park', 'NA', 'SNA', ''),
('WS6', 'Washington Nationals', 'Olympics Grounds', 'NA', 'WNT', ''),
('BSN', 'Boston Red Caps', 'South End Grounds I', 'NL', 'ATL', ''),
('CHN', 'Chicago White Stockings', '23rd Street Grounds', 'NL', 'CHC', ''),
('CN1', 'Cincinnati Reds', 'Avenue Grounds', 'NL', 'CNR', ''),
('HAR', 'Hartford Dark Blues', 'Hartford Ball Club Grounds', 'NL', 'HAR', ''),
('LS1', 'Louisville Grays', 'Louisville Baseball Park', 'NL', 'LGR', ''),
('NY3', 'New York Mutuals', 'Union Grounds (Brooklyn)', 'NL', 'NYU', ''),
('PHN', 'Philadelphia Athletics', 'Jefferson Street Grounds', 'NL', 'ATH', ''),
('SL3', 'St. Louis Brown Stockings', 'Sportsman\'s Park I', 'NL', 'SBS', ''),
('HAR', 'Hartford Dark Blues', 'Union Grounds (Brooklyn)', 'NL', 'HAR', ''),
('CHN', 'Chicago White Stockings', 'Lake Front Park I', 'NL', 'CHC', ''),
('IN1', 'Indianapolis Blues', 'South Street Park', 'NL', 'IBL', ''),
('ML2', 'Milwaukee Grays', 'Eclipse Park II', 'NL', 'MLG', ''),
('PRO', 'Providence Grays', 'Messer Street Grounds', 'NL', 'PRO', ''),
('BFN', 'Buffalo Bisons', 'Riverside Park', 'NL', 'BUF', ''),
('CL2', 'Cleveland Blues', 'Kennard Street Park', 'NL', 'CBL', ''),
('SR1', 'Syracuse Stars', 'Newell Park', 'NL', 'SYR', ''),
('TRN', 'Troy Trojans', 'Putnam Grounds', 'NL', 'TRT', ''),
('CN1', 'Cincinnati Reds', 'Bank Street Grounds', 'NL', 'CNR', ''),
('TRN', 'Troy Trojans', 'Haymakers\' Grounds', 'NL', 'TRT', ''),
('WOR', 'Worcester Ruby Legs', 'Worcester Driving Park Grounds', 'NL', 'WOR', ''),
('DTN', 'Detroit Wolverines', 'Recreation Park', 'NL', 'DTN', ''),
('BL2', 'Baltimore Orioles', 'Newington Park', 'AA', 'BLO', ''),
('CHN', 'Chicago White Stockings', 'Lake Front Park I/Lake Front Park II', 'NL', 'CHC', ''),
('CN2', 'Cincinnati Red Stockings', 'Bank Street Grounds', 'AA', 'CIN', ''),
('LS2', 'Louisville Eclipse', 'Eclipse Park I', 'AA', 'LOU', ''),
('PH4', 'Philadelphia Athletics', 'Oakdale Park', 'AA', 'PHA', ''),
('PT1', 'Pittsburg Alleghenys', 'Exposition Park I', 'AA', 'PIT', ''),
('SL4', 'St. Louis Brown Stockings', 'Sportsman\'s Park I', 'AA', 'STL', ''),
('TRN', 'Troy Trojans', 'Troy Ball Club Grounds', 'NL', 'TRT', ''),
('BL2', 'Baltimore Orioles', 'Oriole Park', 'AA', 'BLO', ''),
('BSN', 'Boston Beaneaters', 'South End Grounds I', 'NL', 'ATL', ''),
('CHN', 'Chicago White Stockings', 'Lake Front Park II', 'NL', 'CHC', ''),
('CL5', 'Columbus Buckeyes', 'Recreation Park I', 'AA', 'CBK', ''),
('NY1', 'New York Gothams', 'Polo Grounds I', 'NL', 'SFG', ''),
('NY4', 'New York Metropolitans', 'Polo Grounds I West Diamond', 'AA', 'NYP', ''),
('PH4', 'Philadelphia Athletics', 'Jefferson Street Grounds', 'AA', 'PHA', ''),
('PHI', 'Philadelphia Quakers', 'Recreation Park', 'NL', 'PHI', ''),
('SL4', 'St. Louis Browns', 'Sportsman\'s Park I', 'AA', 'STL', ''),
('ALT', 'Altoona Mountain City', '', 'UA', 'ALT', ''),
('BFN', 'Buffalo Bisons', 'Olympic Park I', 'NL', 'BUF', ''),
('BLU', 'Baltimore Monumentals', '', 'UA', 'BLU', ''),
('BR3', 'Brooklyn Atlantics', 'Washington Park I', 'AA', 'LAD', ''),
('BSU', 'Boston Reds', '', 'UA', 'BRD', ''),
('CHU', 'Chicago/Pittsburgh (Union League)', '', 'UA', 'CPI', ''),
('CN2', 'Cincinnati Red Stockings', 'League Park I in Cincinnati', 'AA', 'CIN', ''),
('CNU', 'Cincinnati Outlaw Reds', '', 'UA', 'COR', ''),
('IN2', 'Indianapolis Hoosiers', 'Seventh Street Park', 'AA', 'IHO', ''),
('KCU', 'Kansas City Cowboys', '', 'UA', 'KCU', ''),
('MLU', 'Milwaukee Brewers', '', 'UA', 'MLU', ''),
('PHU', 'Philadelphia Keystones', '', 'UA', 'PHK', ''),
('PT1', 'Pittsburg Alleghenys', 'Recreation Park', 'AA', 'PIT', ''),
('RIC', 'Richmond Virginians', 'Allen Pasture', 'AA', 'RIC', ''),
('SLU', 'St. Louis Maroons', '', 'UA', 'SLM', ''),
('SPU', 'St. Paul White Caps', '', 'UA', 'STP', ''),
('TL1', 'Toledo Blue Stockings', 'League Park', 'AA', 'TOL', ''),
('WIL', 'Wilmington Quicksteps', '', 'UA', 'WIL', ''),
('WS7', 'Washington Nationals', 'Athletic Park', 'AA', 'WST', ''),
('WSU', 'Washington Nationals', '', 'UA', 'WNA', ''),
('BR3', 'Brooklyn Grays', 'Washington Park I', 'AA', 'LAD', ''),
('CHN', 'Chicago White Stockings', 'West Side Park I', 'NL', 'CHC', ''),
('LS2', 'Louisville Colonels', 'Eclipse Park I', 'AA', 'LOU', ''),
('NY1', 'New York Giants', 'Polo Grounds I', 'NL', 'SFG', ''),
('SL5', 'St. Louis Maroons', 'Sportsman\'s Park I', 'NL', 'SLM', ''),
('KCN', 'Kansas City Cowboys', 'Association Park', 'NL', 'KCN', ''),
('NY4', 'New York Metropolitans', 'St. George Cricket Grounds', 'AA', 'NYP', ''),
('WS8', 'Washington Nationals', 'Swampdoodle Grounds', 'NL', 'WNL', ''),
('CL3', 'Cleveland Blues', 'National League Park II', 'AA', 'CLV', ''),
('IN3', 'Indianapolis Hoosiers', 'Athletic Park I', 'NL', 'IND', ''),
('PHI', 'Philadelphia Quakers', 'Philadelphia Baseball Grounds', 'NL', 'PHI', ''),
('PIT', 'Pittsburg Alleghenys', 'Recreation Park', 'NL', 'PIT', ''),
('BR3', 'Brooklyn Bridegrooms', 'Washington Park I', 'AA', 'LAD', ''),
('BSN', 'Boston Beaneaters', 'South End Grounds II', 'NL', 'ATL', ''),
('IN3', 'Indianapolis Hoosiers', 'Athletic Park II', 'NL', 'IND', ''),
('KC2', 'Kansas City Cowboys', 'Association Park I', 'AA', 'KCC', ''),
('CL4', 'Cleveland Spiders', 'National League Park', 'NL', 'CLV', ''),
('CL6', 'Columbus Solons', 'Recreation Park II', 'AA', 'CLS', ''),
('KC2', 'Kansas City Cowboys', 'Exposition Park', 'AA', 'KCC', ''),
('NY1', 'New York Giants', 'Polo Grounds II', 'NL', 'SFG', ''),
('BFP', 'Buffalo Bisons', '', 'PL', 'BFB', ''),
('BL3', 'Baltimore Orioles', 'Oriole Park', 'AA', 'BLO', ''),
('BR4', 'Brooklyn Gladiators', 'Ridgewood Park', 'AA', 'BRG', ''),
('BRO', 'Brooklyn Bridegrooms', 'Washington Park II', 'NL', 'LAD', ''),
('BRP', 'Brooklyn Ward\'s Wonders', '', 'PL', 'BWW', ''),
('BSP', 'Boston Reds', '', 'PL', 'BRS', ''),
('CHN', 'Chicago Colts', 'West Side Park I', 'NL', 'CHC', ''),
('CHP', 'Chicago Pirates', '', 'PL', 'CHP', ''),
('CIN', 'Cincinnati Reds', 'League Park I in Cincinnati', 'NL', 'CIN', ''),
('CLP', 'Cleveland Infants', '', 'PL', 'CLI', ''),
('NYP', 'New York Giants', '', 'PL', 'NYI', ''),
('PHI', 'Philadelphia Phillies', 'Philadelphia Baseball Grounds', 'NL', 'PHI', ''),
('PHP', 'Philadelphia Athletics', '', 'PL', 'PHQ', ''),
('PTP', 'Pittsburgh Burghers', '', 'PL', 'PBB', ''),
('RC2', 'Rochester Broncos', 'Culver Field I', 'AA', 'ROC', ''),
('SR2', 'Syracuse Stars', 'Star Park II', 'AA', 'SYS', ''),
('TL2', 'Toledo Maumees', 'Speranza Park', 'AA', 'TLM', ''),
('BL3', 'Baltimore Orioles', 'Union Park', 'AA', 'BLO', ''),
('BRO', 'Brooklyn Grooms', 'Eastern Park', 'NL', 'LAD', ''),
('BS2', 'Boston Reds', 'Congress Street Grounds', 'AA', 'BRS', ''),
('CHN', 'Chicago Colts', 'South Side Park I', 'NL', 'CHC', ''),
('CL4', 'Cleveland Spiders', 'League Park I', 'NL', 'CLV', ''),
('CN3', 'Cincinnati Kelly\'s Killers', 'East End Park', 'AA', 'CKK', ''),
('ML3', 'Milwaukee Brewers', 'Athletic Field', 'AA', 'MLA', ''),
('NY1', 'New York Giants', 'Polo Grounds III', 'NL', 'SFG', ''),
('PH4', 'Philadelphia Athletics', 'Athletic Park', 'AA', 'PHQ', ''),
('PIT', 'Pittsburgh Pirates', 'Exposition Park', 'NL', 'PIT', ''),
('WS9', 'Washington Statesmen', 'Boundary Field', 'AA', 'WAS', ''),
('BLN', 'Baltimore Orioles', 'Union Park', 'NL', 'BLO', ''),
('LS3', 'Louisville Colonels', 'Eclipse Park I', 'NL', 'LOU', ''),
('SLN', 'St. Louis Browns', 'Sportsman\'s Park I', 'NL', 'STL', ''),
('WAS', 'Washington Senators', 'Boundary Field', 'NL', 'WAS', ''),
('LS3', 'Louisville Colonels', 'Eclipse Park II', 'NL', 'LOU', ''),
('SLN', 'St. Louis Browns', 'Robison Field', 'NL', 'STL', ''),
('BSN', 'Boston Beaneaters', 'South End Grounds II / Congress Street Grounds / South End Grounds III', 'NL', 'ATL', ''),
('CHN', 'Chicago Colts', 'West Side Park II', 'NL', 'CHC', ''),
('CIN', 'Cincinnati Reds', 'League Park II in Cincinnati', 'NL', 'CIN', ''),
('BSN', 'Boston Beaneaters', 'South End Grounds III', 'NL', 'ATL', ''),
('PHI', 'Philadelphia Phillies', 'Baker Bowl', 'NL', 'PHI', ''),
('BRO', 'Brooklyn Bridegrooms', 'Eastern Park', 'NL', 'LAD', ''),
('BRO', 'Brooklyn Bridegrooms', 'Washington Park III', 'NL', 'LAD', ''),
('CHN', 'Chicago Orphans', 'West Side Park II', 'NL', 'CHC', ''),
('BRO', 'Brooklyn Superbas', 'Washington Park III', 'NL', 'LAD', ''),
('SLN', 'St. Louis Perfectos', 'Robison Field', 'NL', 'STL', ''),
('SLN', 'St. Louis Cardinals', 'Robison Field', 'NL', 'STL', ''),
('BLA', 'Baltimore Orioles', 'Oriole Park', 'AL', 'NYY', ''),
('BOS', 'Boston Americans', 'Huntington Avenue Grounds', 'AL', 'BOS', ''),
('CHA', 'Chicago White Sox', 'South Side Park II', 'AL', 'CHW', ''),
('CLE', 'Cleveland Blues', 'League Park I', 'AL', 'CLE', ''),
('DET', 'Detroit Tigers', 'Bennett Park', 'AL', 'DET', ''),
('MLA', 'Milwaukee Brewers', 'Lloyd Street Grounds', 'AL', 'BAL', ''),
('PHA', 'Philadelphia Athletics', 'Columbia Park', 'AL', 'OAK', ''),
('WS1', 'Washington Senators', 'American League Park I', 'AL', 'MIN', ''),
('CIN', 'Cincinnati Reds', 'Palace of the Fans', 'NL', 'CIN', ''),
('CLE', 'Cleveland Bronchos', 'League Park I', 'AL', 'CLE', ''),
('SLA', 'St. Louis Browns', 'Sportsman\'s Park III', 'AL', 'BAL', ''),
('CHN', 'Chicago Cubs', 'West Side Park II', 'NL', 'CHC', ''),
('CLE', 'Cleveland Naps', 'League Park I', 'AL', 'CLE', ''),
('NYA', 'New York Highlanders', 'Hilltop Park', 'AL', 'NYY', ''),
('WS1', 'Washington Senators', 'American League Park II', 'AL', 'MIN', ''),
('BSN', 'Boston Doves', 'South End Grounds III', 'NL', 'ATL', ''),
('BOS', 'Boston Red Sox', 'Huntington Avenue Grounds', 'AL', 'BOS', ''),
('PHA', 'Philadelphia Athletics', 'Shibe Park', 'AL', 'OAK', ''),
('PIT', 'Pittsburgh Pirates', 'Exposition Park/Forbes Field', 'NL', 'PIT', ''),
('SLA', 'St. Louis Browns', 'Sportsman\'s Park IV', 'AL', 'BAL', ''),
('CHA', 'Chicago White Sox', 'South Side Park II/Comiskey Park', 'AL', 'CHW', ''),
('CLE', 'Cleveland Naps', 'League Park II', 'AL', 'CLE', ''),
('PIT', 'Pittsburgh Pirates', 'Forbes Field', 'NL', 'PIT', ''),
('BRO', 'Brooklyn Dodgers', 'Washington Park III', 'NL', 'LAD', ''),
('BSN', 'Boston Rustlers', 'South End Grounds III', 'NL', 'ATL', ''),
('CHA', 'Chicago White Sox', 'Comiskey Park', 'AL', 'CHW', ''),
('NY1', 'New York Giants', 'Polo Grounds III/Polo Grounds IV', 'NL', 'SFG', ''),
('WS1', 'Washington Senators', 'Griffith Stadium I', 'AL', 'MIN', ''),
('BOS', 'Boston Red Sox', 'Fenway Park I', 'AL', 'BOS', ''),
('BSN', 'Boston Braves', 'South End Grounds III', 'NL', 'ATL', ''),
('CIN', 'Cincinnati Reds', 'Crosley Field', 'NL', 'CIN', ''),
('DET', 'Detroit Tigers', 'Navin Field', 'AL', 'DET', ''),
('NY1', 'New York Giants', 'Polo Grounds IV', 'NL', 'SFG', ''),
('BRO', 'Brooklyn Superbas', 'Ebbets Field', 'NL', 'LAD', ''),
('NYA', 'New York Yankees', 'Polo Grounds IV', 'AL', 'NYY', ''),
('BLF', 'Baltimore Terrapins', '', 'FL', 'BLT', ''),
('BRF', 'Brooklyn Tip-Tops', '', 'FL', 'BTT', ''),
('BRO', 'Brooklyn Robins', 'Ebbets Field', 'NL', 'LAD', ''),
('BUF', 'Buffalo Buffeds', '', 'FL', 'BFL', ''),
('CHF', 'Chicago Chi-Feds', 'Wrigley Field', 'FL', 'CHH', ''),
('IND', 'Indianapolis Hoosiers', '', 'FL', 'NEW', ''),
('KCF', 'Kansas City Packers', '', 'FL', 'KCP', ''),
('PTF', 'Pittsburgh Rebels', '', 'FL', 'PBS', ''),
('SLF', 'St. Louis Terriers', '', 'FL', 'SLI', ''),
('BSN', 'Boston Braves', 'Fenway Park I / Braves Field', 'NL', 'ATL', ''),
('BUF', 'Buffalo Blues', '', 'FL', 'BFL', ''),
('CHF', 'Chicago Whales', 'Wrigley Field', 'FL', 'CHH', ''),
('CLE', 'Cleveland Indians', 'League Park II', 'AL', 'CLE', ''),
('NEW', 'Newark Pepper', '', 'FL', 'NEW', ''),
('BSN', 'Boston Braves', 'Braves Field', 'NL', 'ATL', ''),
('CHN', 'Chicago Cubs', 'Wrigley Field', 'NL', 'CHC', ''),
('SLN', 'St. Louis Cardinals', 'Robison Field/Sportsman\'s Park IV', 'NL', 'STL', ''),
('SLN', 'St. Louis Cardinals', 'Sportsman\'s Park IV', 'NL', 'STL', ''),
('NYA', 'New York Yankees', 'Yankee Stadium I', 'AL', 'NYY', ''),
('BRO', 'Brooklyn Dodgers', 'Ebbets Field', 'NL', 'LAD', ''),
('CLE', 'Cleveland Indians', 'League Park II/Cleveland Stadium', 'AL', 'CLE', ''),
('BOS', 'Boston Red Sox', 'Fenway Park II', 'AL', 'BOS', ''),
('BSN', 'Boston Bees', 'Braves Field', 'NL', 'ATL', ''),
('DET', 'Detroit Tigers', 'Briggs Stadium', 'AL', 'DET', ''),
('PHI', 'Philadelphia Phillies', 'Baker Bowl/Shibe Park', 'NL', 'PHI', ''),
('PHI', 'Philadelphia Phillies', 'Shibe Park', 'NL', 'PHI', ''),
('PHI', 'Philadelphia Blue Jays', 'Shibe Park', 'NL', 'PHI', ''),
('CLE', 'Cleveland Indians', 'Cleveland Stadium', 'AL', 'CLE', ''),
('ML1', 'Milwaukee Braves', 'County Stadium', 'NL', 'ATL', ''),
('PHA', 'Philadelphia Athletics', 'Connie Mack Stadium', 'AL', 'OAK', ''),
('PHI', 'Philadelphia Phillies', 'Connie Mack Stadium', 'NL', 'PHI', ''),
('BAL', 'Baltimore Orioles', 'Memorial Stadium', 'AL', 'BAL', ''),
('CIN', 'Cincinnati Redlegs', 'Crosley Field', 'NL', 'CIN', ''),
('KC1', 'Kansas City Athletics', 'Municipal Stadium I', 'AL', 'OAK', ''),
('WS1', 'Washington Senators', 'Griffith Stadium II', 'AL', 'MIN', ''),
('LAN', 'Los Angeles Dodgers', 'Los Angeles Memorial Coliseum', 'NL', 'LAD', ''),
('SFN', 'San Francisco Giants', 'Seals Stadium', 'NL', 'SFG', ''),
('SFN', 'San Francisco Giants', 'Candlestick Park', 'NL', 'SFG', ''),
('DET', 'Detroit Tigers', 'Tiger Stadium', 'AL', 'DET', ''),
('LAA', 'Los Angeles Angels', 'Wrigley Field (LA)', 'AL', 'ANA', ''),
('MIN', 'Minnesota Twins', 'Metropolitan Stadium', 'AL', 'MIN', ''),
('WS2', 'Washington Senators', 'Griffith Stadium II', 'AL', 'TEX', ''),
('HOU', 'Houston Colt .45\'s', 'Colt Stadium', 'NL', 'HOU', ''),
('LAA', 'Los Angeles Angels', 'Dodger Stadium', 'AL', 'ANA', ''),
('LAN', 'Los Angeles Dodgers', 'Dodger Stadium', 'NL', 'LAD', ''),
('NYN', 'New York Mets', 'Polo Grounds IV', 'NL', 'NYM', ''),
('WS2', 'Washington Senators', 'R.F.K. Stadium', 'AL', 'TEX', ''),
('NYN', 'New York Mets', 'Shea Stadium', 'NL', 'NYM', ''),
('CAL', 'California Angels', 'Dodger Stadium', 'AL', 'ANA', ''),
('HOU', 'Houston Astros', 'Astrodome', 'NL', 'HOU', ''),
('ATL', 'Atlanta Braves', 'Atlanta-Fulton County Stadium', 'NL', 'ATL', ''),
('CAL', 'California Angels', 'Anaheim Stadium', 'AL', 'ANA', ''),
('SLN', 'St. Louis Cardinals', 'Sportsman\'s Park IV/Busch Stadium II', 'NL', 'STL', ''),
('SLN', 'St. Louis Cardinals', 'Busch Stadium II', 'NL', 'STL', ''),
('OAK', 'Oakland Athletics', 'Oakland Coliseum', 'AL', 'OAK', ''),
('ATL', 'Atlanta Braves', 'Atlanta-Fulton County Stadium', 'NL', 'ATL', 'W'),
('BAL', 'Baltimore Orioles', 'Memorial Stadium', 'AL', 'BAL', 'E'),
('BOS', 'Boston Red Sox', 'Fenway Park II', 'AL', 'BOS', 'E'),
('CAL', 'California Angels', 'Anaheim Stadium', 'AL', 'ANA', 'W'),
('CHA', 'Chicago White Sox', 'Comiskey Park', 'AL', 'CHW', 'W'),
('CHN', 'Chicago Cubs', 'Wrigley Field', 'NL', 'CHC', 'E'),
('CIN', 'Cincinnati Reds', 'Crosley Field', 'NL', 'CIN', 'W'),
('CLE', 'Cleveland Indians', 'Cleveland Stadium', 'AL', 'CLE', 'E'),
('DET', 'Detroit Tigers', 'Tiger Stadium', 'AL', 'DET', 'E'),
('HOU', 'Houston Astros', 'Astrodome', 'NL', 'HOU', 'W'),
('KCA', 'Kansas City Royals', 'Municipal Stadium II', 'AL', 'KCR', 'W'),
('LAN', 'Los Angeles Dodgers', 'Dodger Stadium', 'NL', 'LAD', 'W'),
('MIN', 'Minnesota Twins', 'Metropolitan Stadium', 'AL', 'MIN', 'W'),
('MON', 'Montreal Expos', 'Jarry Park', 'NL', 'WSN', 'E'),
('NYA', 'New York Yankees', 'Yankee Stadium I', 'AL', 'NYY', 'E'),
('NYN', 'New York Mets', 'Shea Stadium', 'NL', 'NYM', 'E'),
('OAK', 'Oakland Athletics', 'Oakland Coliseum', 'AL', 'OAK', 'W'),
('PHI', 'Philadelphia Phillies', 'Connie Mack Stadium', 'NL', 'PHI', 'E'),
('PIT', 'Pittsburgh Pirates', 'Forbes Field', 'NL', 'PIT', 'E'),
('SDN', 'San Diego Padres', 'Jack Murphy Stadium', 'NL', 'SDP', 'W'),
('SE1', 'Seattle Pilots', 'Sicks Stadium', 'AL', 'MIL', 'W'),
('SFN', 'San Francisco Giants', 'Candlestick Park', 'NL', 'SFG', 'W'),
('SLN', 'St. Louis Cardinals', 'Busch Stadium II', 'NL', 'STL', 'E'),
('WS2', 'Washington Senators', 'R.F.K. Stadium', 'AL', 'TEX', 'E'),
('CIN', 'Cincinnati Reds', 'Crosley Field/Riverfront Stadium', 'NL', 'CIN', 'W'),
('ML4', 'Milwaukee Brewers', 'County Stadium', 'AL', 'MIL', 'W'),
('PIT', 'Pittsburgh Pirates', 'Forbes Field/Three Rivers Stadium', 'NL', 'PIT', 'E'),
('CIN', 'Cincinnati Reds', 'Riverfront Stadium', 'NL', 'CIN', 'W'),
('PHI', 'Philadelphia Phillies', 'Veterans Stadium', 'NL', 'PHI', 'E'),
('PIT', 'Pittsburgh Pirates', 'Three Rivers Stadium', 'NL', 'PIT', 'E'),
('ML4', 'Milwaukee Brewers', 'County Stadium', 'AL', 'MIL', 'E'),
('TEX', 'Texas Rangers', 'Arlington Stadium', 'AL', 'TEX', 'W'),
('KCA', 'Kansas City Royals', 'Royals Stadium', 'AL', 'KCR', 'W'),
('NYA', 'New York Yankees', 'Shea Stadium', 'AL', 'NYY', 'E'),
('NYA', 'New York Yankees', 'Yankee Stadium II', 'AL', 'NYY', 'E'),
('MON', 'Montreal Expos', 'Stade Olympique', 'NL', 'WSN', 'E'),
('SEA', 'Seattle Mariners', 'Kingdome', 'AL', 'SEA', 'W'),
('TOR', 'Toronto Blue Jays', 'Exhibition Stadium', 'AL', 'TOR', 'E'),
('MIN', 'Minnesota Twins', 'Hubert H Humphrey Metrodome', 'AL', 'MIN', 'W'),
('TOR', 'Toronto Blue Jays', 'Exhibition Stadium /Skydome', 'AL', 'TOR', 'E'),
('TOR', 'Toronto Blue Jays', 'Skydome', 'AL', 'TOR', 'E'),
('CHA', 'Chicago White Sox', 'Comiskey Park II', 'AL', 'CHW', 'W'),
('BAL', 'Baltimore Orioles', 'Oriole Park at Camden Yards', 'AL', 'BAL', 'E'),
('COL', 'Colorado Rockies', 'Mile High Stadium', 'NL', 'COL', 'W'),
('FLO', 'Florida Marlins', 'Joe Robbie Stadium', 'NL', 'FLA', 'E'),
('KCA', 'Kansas City Royals', 'Kauffman Stadium', 'AL', 'KCR', 'W'),
('ATL', 'Atlanta Braves', 'Atlanta-Fulton County Stadium', 'NL', 'ATL', 'E'),
('CHA', 'Chicago White Sox', 'Comiskey Park II', 'AL', 'CHW', 'C'),
('CHN', 'Chicago Cubs', 'Wrigley Field', 'NL', 'CHC', 'C'),
('CIN', 'Cincinnati Reds', 'Riverfront Stadium', 'NL', 'CIN', 'C'),
('CLE', 'Cleveland Indians', 'Jacobs Field', 'AL', 'CLE', 'C'),
('HOU', 'Houston Astros', 'Astrodome', 'NL', 'HOU', 'C'),
('KCA', 'Kansas City Royals', 'Kauffman Stadium', 'AL', 'KCR', 'C'),
('MIN', 'Minnesota Twins', 'Hubert H Humphrey Metrodome', 'AL', 'MIN', 'C'),
('ML4', 'Milwaukee Brewers', 'County Stadium', 'AL', 'MIL', 'C'),
('PIT', 'Pittsburgh Pirates', 'Three Rivers Stadium', 'NL', 'PIT', 'C'),
('SLN', 'St. Louis Cardinals', 'Busch Stadium II', 'NL', 'STL', 'C'),
('TEX', 'Texas Rangers', 'The Ballpark at Arlington', 'AL', 'TEX', 'W'),
('COL', 'Colorado Rockies', 'Coors Field', 'NL', 'COL', 'W'),
('ANA', 'Anaheim Angels', 'Edison International Field', 'AL', 'ANA', 'W'),
('ATL', 'Atlanta Braves', 'Turner Field', 'NL', 'ATL', 'E'),
('CIN', 'Cincinnati Reds', 'Cinergy Field', 'NL', 'CIN', 'C'),
('SDN', 'San Diego Padres', 'Qualcomm Stadium', 'NL', 'SDP', 'W'),
('SFN', 'San Francisco Giants', '3Com Park', 'NL', 'SFG', 'W'),
('ARI', 'Arizona Diamondbacks', 'Bank One Ballpark', 'NL', 'ARI', 'W'),
('DET', 'Detroit Tigers', 'Tiger Stadium', 'AL', 'DET', 'C'),
('MIL', 'Milwaukee Brewers', 'County Stadium', 'NL', 'MIL', 'C'),
('TBA', 'Tampa Bay Devil Rays', 'Tropicana Field', 'AL', 'TBD', 'E'),
('FLO', 'Florida Marlins', 'Pro Player Stadium', 'NL', 'FLA', 'E'),
('SEA', 'Seattle Mariners', 'Kingdome / Safeco Field', 'AL', 'SEA', 'W'),
('DET', 'Detroit Tigers', 'Comerica Park', 'AL', 'DET', 'C'),
('HOU', 'Houston Astros', 'Enron Field', 'NL', 'HOU', 'C'),
('SEA', 'Seattle Mariners', 'Safeco Field', 'AL', 'SEA', 'W'),
('SFN', 'San Francisco Giants', 'PacBell Park', 'NL', 'SFG', 'W'),
('MIL', 'Milwaukee Brewers', 'Miller Park', 'NL', 'MIL', 'C'),
('PIT', 'Pittsburgh Pirates', 'PNC Park', 'NL', 'PIT', 'C'),
('HOU', 'Houston Astros', 'Minute Maid Park', 'NL', 'HOU', 'C'),
('CHA', 'Chicago White Sox', 'U.S. Cellular Field', 'AL', 'CHW', 'C'),
('CIN', 'Cincinnati Reds', 'Great American Ball Park', 'NL', 'CIN', 'C'),
('MON', 'Montreal Expos', 'Stade Olympique/Hiram Bithorn Stadium', 'NL', 'WSN', 'E'),
('ANA', 'Anaheim Angels', 'Angels Stadium of Anaheim', 'AL', 'ANA', 'W'),
('OAK', 'Oakland Athletics', 'Network Associates Coliseum', 'AL', 'OAK', 'W'),
('PHI', 'Philadelphia Phillies', 'Citizens Bank Park', 'NL', 'PHI', 'E'),
('SDN', 'San Diego Padres', 'Petco Park', 'NL', 'SDP', 'W'),
('SFN', 'San Francisco Giants', 'SBC Park', 'NL', 'SFG', 'W'),
('FLO', 'Florida Marlins', 'Dolphin Stadium', 'NL', 'FLA', 'E'),
('LAA', 'Los Angeles Angels of Anaheim', 'Angel Stadium', 'AL', 'ANA', 'W'),
('OAK', 'Oakland Athletics', 'McAfee Coliseum', 'AL', 'OAK', 'W'),
('TEX', 'Texas Rangers', 'Ameriquest Field', 'AL', 'TEX', 'W'),
('TOR', 'Toronto Blue Jays', 'Rogers Centre', 'AL', 'TOR', 'E'),
('WAS', 'Washington Nationals', 'R.F.K. Stadium', 'NL', 'WSN', 'E'),
('ARI', 'Arizona Diamondbacks', 'Chase Field', 'NL', 'ARI', 'W'),
('SFN', 'San Francisco Giants', 'AT&T Park', 'NL', 'SFG', 'W'),
('SLN', 'St. Louis Cardinals', 'Busch Stadium III', 'NL', 'STL', 'C'),
('TEX', 'Texas Rangers', 'Rangers Ballpark in Arlington', 'AL', 'TEX', 'W'),
('TBA', 'Tampa Bay Rays', 'Tropicana Field', 'AL', 'TBD', 'E'),
('WAS', 'Washington Nationals', 'Nationals Park', 'NL', 'WSN', 'E'),
('NYA', 'New York Yankees', 'Yankee Stadium III', 'AL', 'NYY', 'E'),
('NYN', 'New York Mets', 'Citi Field', 'NL', 'NYM', 'E'),
('OAK', 'Oakland Athletics', 'Oakland-Alameda County Coliseum', 'AL', 'OAK', 'W'),
('MIN', 'Minnesota Twins', 'Target Field', 'AL', 'MIN', 'C'),
('FLO', 'Florida Marlins', 'Sun Life Stadium', 'NL', 'FLA', 'E'),
('CLE', 'Cleveland Indians', 'Progressive Field', 'AL', 'CLE', 'C'),
('LAA', 'Los Angeles Angels of Anaheim', 'Angel Stadium of Anaheim', 'AL', 'ANA', 'W'),
('MIA', 'Miami Marlins', 'Marlins Park', 'NL', 'FLA', 'E'),
('OAK', 'Oakland Athletics', 'O.co Coliseum', 'AL', 'OAK', 'W'),
('HOU', 'Houston Astros', 'Minute Maid Park', 'AL', 'HOU', 'W'),
('ATL', 'Atlanta Braves', 'SunTrust Park', 'NL', 'ATL', 'E'),
('CHA', 'Chicago White Sox', 'Guaranteed Rate Field', 'AL', 'CHW', 'C'),
('TEX', 'Texas Rangers', 'Globe Life Park in Arlington', 'AL', 'TEX', 'W'),
('SEA', 'Seattle Mariners', 'T-Mobile Park', 'AL', 'SEA', 'W'),
('SFN', 'San Francisco Giants', 'Oracle Park', 'NL', 'SFG', 'W'),
('TEX', 'Texas Rangers', 'Globe Life Field', 'AL', 'TEX', 'W'),
('TOR', 'Toronto Blue Jays', 'Sahlen Field', 'AL', 'TOR', 'E');
